### PR TITLE
Fix missing option on typings

### PR DESCRIPTION
**Pull request by csprance**
Fixed typings on missing option

```js
noAliasPropagation?: boolean | 'first-only';
```

### CODE REVIEW

**Comment by Alhadis** [comment]
I played around with this a bit locally and noticed the typings require all three arguments to be passed:

```typescript
// test.ts
import getOpts from "get-options";
console.log(getOpts(["--help", "--verbose"], {
    "--help, -?": "",
    "--verbose":  "",
}));
```

```console
λ tsc test.ts
test.ts:2:13 - error TS2554: Expected 3 arguments, but got 2.

2 console.log(getOpts(["--help", "--verbose"], {
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3     "--help, -?": "",
  ~~~~~~~~~~~~~~~~~~~~~
4     "--verbose":  "",
  ~~~~~~~~~~~~~~~~~~~~~
5 }));
  ~~

  node_modules/get-options/index.d.ts:20:2
    20  config: Config
        ~~~~~~~~~~~~~~
    An argument for 'config' was not provided.
```

Both the second and third arguments are actually optional (`optdef` should probably have a default value in the function header to communicate this better...). Basically, if you don't define anything specific, it [tries to do the right thing](https://github.com/Alhadis/GetOptions/blob/master/docs/anonymous-options.md) with its input.

Would it be possible to amend the typings to reflect this?

**Comment by csprance** [comment]
I updated the PR

**Comment by Alhadis** [comment]
Thanks! Sorry for the delay.

I decided I'm going to adjust the behaviour of `getOpts` a little so it handles string arguments a little better. Currently, `getOpts("--help")` is decoded as `["-", "-", "h", "e", "l", "p"]`, whereas a much more realistic interpretation would be `{help: true}`. What would need to be changed in the typings to reflect this?

The change of semantics is largely inspired by the need to parse environment variables like `NODE_OPTIONS` and co, which may or may not contain quoted values with spaces (which complicate accurate parsing).

**Comment by csprance** [comment]
Hmm, good question. I guess if you want to start a new branch with your changes I can take a look at it and see what the typings would look like.

Can you create a new version on npm 1.1.3 with the updates for the types?

**Comment by Alhadis** [comment]
Shit! Sorry mate, I was meant to do this earlier, but I got sidetracked. 😞

Will cut a release now.

**Comment by Alhadis** [comment]
Alright, the string-handling behaviour was implemented in [`bf7a188`](https://github.com/Alhadis/GetOptions/commit/bf7a1882c8615b41f756736166ec1b46c3e03f2c). I'm guessing this would be all that's needed for the typings?

~~~diff
diff --git a/index.d.ts b/index.d.ts
index b2a04b3..c8f2e1c 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -7,7 +7,7 @@
  * Extract command-line options from a list of strings.
  */
 declare function getOpts(
-	input: any[],
+	input: string | any[],
 	optdef?: string | { [key: string]: string },
 	config?: getOpts.Config
 ): getOpts.Options;
~~~

Hold off on any PRs though, I intend to add new options for features I've been wanting to implement. I'll ping you for review before cutting the next release. 😉

**Pull request merged**
